export default {
  ACTIVATE_PAD: 'ACTIVATE_PAD',
  DEACTIVATE_PAD: 'DEACTIVATE_PAD',
  SET_OUTPUT_DEVICE: 'SET_OUTPUT_DEVICE',
  SET_OUTPUT_DEVICE_FAILED: 'SET_OUTPUT_DEVICE_FAILED',
  SET_SAMPLE_FROM_BLOB: 'SET_SAMPLE_FROM_BLOB',
  SET_SAMPLE_TITLE: 'SET_SAMPLE_TITLE',
  TOGGLE_SAMPLE_REPEAT: 'TOGGLE_SAMPLE_REPEAT',
  TOGGLE_SAMPLE_TOGGLE: 'TOGGLE_SAMPLE_TOGGLE'
}
